FROM public.ecr.aws/lambda/python:3.13

WORKDIR /app

ARG SPOTIFY_ID
ARG SPOTIFY_SECRET
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION

ENV SPOTIFY_ID=$SPOTIFY_ID
ENV SPOTIFY_SECRET=$SPOTIFY_SECRET
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

COPY . /app/

RUN python3 -m pip install -r requirements.txt

CMD [ "main.lambda_handler" ]