# Use AWS Lambda Python base image
FROM public.ecr.aws/lambda/python:3.13

WORKDIR ${LAMBDA_TASK_ROOT}

ARG SPOTIFY_ID \
	SPOTIFY_SECRET \
	AWS_ACCESS_KEY_ID \
	AWS_SECRET_ACCESS_KEY \
	AWS_DEFAULT_REGION \
	SPOTIFY_REDIRECT_URI

ENV SPOTIFY_ID=${SPOTIFY_ID} \
	SPOTIFY_SECRET=${SPOTIFY_SECRET} \
	AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
	AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
	AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} \
	SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY main.py .

CMD [ "main.lambda_handler" ]