[project]
name = "update-playlist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.37.37",
    "spotipy>=2.25.1",
]
